[project]
name = "mcp-example"
version = "0.0.1"
description = "An MCP Example"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi-mcp>=0.4.0",
    "llama-index>=0.14.10",
    "llama-index-llms-ollama>=0.9.0",
    "llama-index-tools-mcp>=0.4.5",
    "mcp[cli]>=1.24.0",
]
